name: pet_match_backend
description: A backend project for pet matching
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  postgres: ^2.5.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mailer: ^5.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

executables:
  pet_match_backend: bin/server.dart  # Esto indica el archivo principal para ejecutarse
